"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
[$os $custom](bg:surface0 fg:text)\
[](fg:surface0 bg:maroon )\
$directory\
[ ](fg:maroon)\
$character"""

right_format = """
[](surface0)\
$git_branch\
$git_status\
$git_metrics\
[](fg:surface0 bg:teal)\
$rust\
$golang\
$nodejs\
$java\
$kotlin\
$python\
[](fg:teal bg:blue)\
$docker_context\
[](fg:blue bg:purple)\
$time\
[](fg:purple)\
"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Ubuntu = "󰕈"
Macos = ""
Linux = "󰌽"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
CentOS = ""
Debian = "󰣚"

[directory]
style = "fg:mantle bg:maroon"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch(:$remote_branch) ](fg:green bg:surface0)]($style)'

[git_status]
style = "bg:teal"
format = '[$all_status](fg:green bg:surface0)($style)'

[git_metrics]
added_style = "fg:green bg:surface0"
deleted_style = "fg:red bg:surface0"
format = "([+$added]($added_style)[-$deleted]($deleted_style))[]($added_style)"
disabled = false

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $context) ](fg:mantle bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:maroon"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[custom.air]
command = "echo -n  "
when = ''' [[ $(hostname) == *"-Air."* ]] '''
style = "bg:surface0 fg:text"

[custom.mini]
command = "echo -n 󰇅"
when = ''' [[ $(hostname) == *"-mini."* ]] '''
style = "bg:surface0 fg:text"

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
